FROM python:3.9-slim-buster
LABEL maintainer="nailbiter"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY common.py .
COPY heartbeat_time.py .

COPY .env .env

CMD ["python3","heartbeat_time.py"]
