version: '3.3'

services:
    heartbeat_habits:
        build:
            context: .
            dockerfile: Dockerfile
        command: python3 heartbeat_habits.py heartbeat
    heartbeat_time:
        build:
            context: .
            dockerfile: Dockerfile  
        command: python3 heartbeat_time.py
    actor:
        build:
            context: .
            dockerfile: Dockerfile  
        command: python3 actor.py
