FROM python:3.9-slim-buster
LABEL maintainer="nailbiter"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir _common
COPY _common/__init__.py _common
COPY _common/simple_math_eval.py _common

COPY _actor.py .

COPY actor.py .
COPY heartbeat_habits.py .
COPY heartbeat_time.py .

COPY .env .env

CMD ["python3","actor.py"]
