FROM python:3.9-slim-buster
LABEL maintainer="nailbiter"

COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN mkdir _common
COPY _common/__init__.py _common
COPY _common/simple_math_eval.py _common

COPY heartbeat_time.py .

COPY .env .env

CMD ["python3","heartbeat_time.py"]
